apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: guardian-forms
  name: guardian-forms
spec:
  replicas: 1
  selector:
    matchLabels:
      service: guardian-forms
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: guardian-forms
    spec:
      containers:
        - image: andrewrisse/guardian-forms
          name: guardian-forms
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_AUTH0_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: REACT_APP_AUTH0_DOMAIN_NAME
            - name: REACT_APP_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: REACT_APP_AUTH0_CLIENT_ID
            - name: REACT_APP_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: REACT_APP_REDIRECT_URL
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: REACT_APP_BACKEND_URL
            - name: REACT_APP_HOME_URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: REACT_APP_HOME_URL
      restartPolicy: Always
