apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: guardian-forms-api
  name: guardian-forms-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: guardian-forms-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: guardian-forms-api
    spec:
      containers:
        - image: andrewrisse/guardian-forms-api
          name: guardian-forms-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
          - name: MONGODB_URI
            valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MONGODB_URI
      restartPolicy: Always

